---
kind: pipeline
type: docker
name: pull-checks

steps:
- name: squashbot
  image: dn42/pipeline
  environment:
   SQUASHBOT_TOKEN:
     from_secret: SQUASHBOT_TOKEN
  commands:
   - /scripts/wrapper

trigger:
  event:
  - pull_request

---
kind: signature
hmac: a7844c78365f463971354b5650affed18c0ca3ffd05e9c96a7c3390558c84fb9

...
